### ISSUE TITLE
[BUG] Fabric install error on ubuntu

### ISSUE THREAD

**Issue by GeneralWiggin** [Drehmal-Team/installer#3]
**Describe the bug**
The progress bar fails to complete when installing fabric via multiplayer option, though the text updates to say successfully installed. looking through logs it appears it may not be simply graphical.

**To Reproduce**
1.  Select multiplayer install option
2. click download button for fabric
3. wait for fabric to install and UI to bug.

**Expected behavior**
Progress bar should complete when fabric is installed. 

**Screenshots**
![image](https://github.com/Drehmal-Team/installer/assets/46917052/c962cc50-479c-4068-ba60-bf63377cd1ea)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04

**Additional context**
this install was performed on a machine that previously had drehmal manually installed and still has old drehmal stuff I am still using.

**Log File**

[13-01-2024_3-installer.log](https://github.com/Drehmal-Team/installer/files/13930365/13-01-2024_3-installer.log)

**Comment by GeneralWiggin** [comment]
this bug also occurs when attempting singleplayer install on same OS.

**Comment by jgaribsin** [comment]
Thanks for the report! This should be fixed with commit [fd6cfda](https://github.com/Drehmal-Team/installer/commit/fd6cfdad6b7db8fea6d58123cc83072c3629bf6e) / version [v0.1.1](https://github.com/Drehmal-Team/installer/releases/tag/v0.1.1).

**Comment by GeneralWiggin** [comment]
![image](https://github.com/Drehmal-Team/installer/assets/46917052/e5e6f80a-b023-4c08-bc49-8abdbea326c3)
issue persists on latest version

**Comment by GeneralWiggin** [comment]
[27-01-2024_2-installer.log](https://github.com/Drehmal-Team/installer/files/14074424/27-01-2024_2-installer.log)
issue persists on latest, have a fresh log

**Comment by GeneralWiggin** [comment]
issue occurs both with an existing populated drehmal/version directory folder from an old copy of drehmal, and an empty drehmal directory. occurs on both singleplayer and multiplayer install options. error is same regardless of above

**Comment by GeneralWiggin** [comment]
[27-01-2024_5-installer.log](https://github.com/Drehmal-Team/installer/files/14074663/27-01-2024_5-installer.log)
heres a log from an attempted fabric install on empty folder

**Comment by GeneralWiggin** [comment]
issue is a client problem, a folder in .minecraft was set to read only. resolved by user
